### ISSUE TITLE
Android Location Services

### ISSUE THREAD

**Issue by AdamDorwart** [TheBurrd/androidClient#17]
We need a class that interfaces with the Android location services and pulls the gps coordinates. Unfortunately this isn't just a simple Location.getCoords(), because it takes time for the device to get a lock.

Check out this StackOverflow to see an example:
http://stackoverflow.com/questions/1513485/how-do-i-get-the-current-gps-location-programmatically-in-android

**Comment by sjatakia** [comment]
![screenshot_2015-05-17-19-10-35_1024](https://cloud.githubusercontent.com/assets/6753916/7673487/379b4d56-fcc9-11e4-8296-7716e3ac0b8a.png)

**Comment by AdamDorwart** [comment]
What branch is this in?
