### ISSUE TITLE
Deal Ratings

### ISSUE THREAD

**Issue by daleebz** [TheBurrd/androidClient#23]
start playing with buttons that increase and modify elements in "data base" that keep an overall count

**Comment by AdamDorwart** [comment]
This issue has almost completed implementation and is awaiting final integration testing with server code. Still need to poll vote state on load of views.

**Comment by AdamDorwart** [comment]
Tracking in branch `saveVotesToParse`

**Comment by AdamDorwart** [comment]
81fac59964140670cbd996e045b6d206b43694bc

Initial client code exist to support up vote and down vote. Displays debug toast messages that will need to be removed. Also need to check if a vote exists when setting up the view.
