### ISSUE TITLE
Restaurant Fetch class

### ISSUE THREAD

**Issue by AdamDorwart** [TheBurrd/androidClient#4]
The purpose of this class is to interface with our REST api. When the user wants to view a specific restaurants page this class will fetch the information from the server and then store it in the model on the client.

This class is used when the restaurant needs to be fetched or updated (requery). It will make updates to the data model stored in the passed ArrayListAdapter

See the Volley android api for more details

**Comment by patelanjali** [comment]
I am not too sure about this one, but I can work with someone on this, and try to learn
