### ISSUE TITLE
Users expect that clicking the burrd header will return them to home or give feedback of somesort

### ISSUE THREAD

**Issue by daleebz** [TheBurrd/androidClient#41]
maybe clicking the burrd header can reset app to default settings ie sort  by rating in 5 mi distance?

**Comment by t1miller** [comment]
We should look into what is the default behavior that users expect to happen when the header is clicked

**Comment by t1miller** [comment]
What exactly should we do when the header is clicked so we can close this issue?

**Comment by AdamDorwart** [comment]
I don't think it's clear what should happen here. Until this can be more explicitly defined it, let's close it.
