### ISSUE TITLE
App crash when Wifi is off 

### ISSUE THREAD

**Issue by patelanjali** [TheBurrd/androidClient#44]
When we click on any functionality, app crash when the wifi is off

**Comment by t1miller** [comment]
Is this a Wifi issue or an internet connection issue? Can someone who has a android device with a cellular connection test this?

**Comment by AdamDorwart** [comment]
I'm unable to replicate but your not the first person to mention a bug with WiFi. I think it's caused by poor error handling for the Parse Queries.

**Comment by t1miller** [comment]
I was able to write a dialog box that enables the user to turn on the wifi if it is turned off but i feel this is just a bandaid to bigger problem.

**Comment by daleebz** [comment]
I haven't had too many problems to be honest with cellular connections

**Comment by t1miller** [comment]
I opened up the debugger and ran the app without wifi. This is the culprit. Maybe Adam can take a look because of his knowledge of the database stuff.

java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
            at com.dgaf.happyhour.Adapter.DealListAdapter$1.done(DealListAdapter.java:146)
            at com.dgaf.happyhour.Adapter.DealListAdapter$1.done(DealListAdapter.java:144)
            at com.parse.Parse$6$1.run(Parse.java:944)

**Comment by AdamDorwart** [comment]
Alright I've been able to replicate this bug by turning on Airplane mode on my device. It is caused by the Parse Query returning an exception but some logcat debugging code still trying to read the result.

**Comment by AdamDorwart** [comment]
Pull request with fix is at #62

@t1miller or @patelanjali , could you pull this branch and verify it solves the issue?
