### ISSUE TITLE
Highlight multiple days of the week

### ISSUE THREAD

**Issue by daleebz** [TheBurrd/androidClient#48]

**Comment by AdamDorwart** [comment]
Resolving issue in `dayOfWeekFilter` branch

**Comment by AdamDorwart** [comment]
5a092cd9808167b233bfec3e64df6b727125eac6

Switched Query parameter model a bitmask representation of week days. Started refactoring code for new interface and adapting changes to allow multiple days of week. Still in progress in DealListAdapter.java

Also needs a Today button added in Navigation Drawer
