### ISSUE TITLE
App Icon

### ISSUE THREAD

**Issue by t1miller** [TheBurrd/androidClient#8]
We need some mockups of App Icons. Here is a link to the dimensions the icons need to be http://developer.android.com/design/media/devices_displays_density@2x.png They also have to be named ic_launcher and need to go in the mipmap-XXXX folders. Each Icon will live in its own mipmap folder that corresponds to its resolution. The lowest resolution goes in mipmap-mdpi the highest in mipmap-xxhdpi.

**Comment by AdamDorwart** [comment]
Icon complete. Pull request #16
