### ISSUE TITLE
enable UI in data entry form to add multiple deals to one restaurant

### ISSUE THREAD

**Issue by daleebz** [TheBurrd/androidClient#83]
I'm thinking like a plus button after the first deal to add another deal object(or two) 
It's incredibly time consuming to go through the process and add multiple deals to a restaurant.

 when you have a restaurant with a bad address (parser messes up and you have a suite # for example)

so you fix that the first time when you input the deal

then the next time you input another deal for the exact same restaurant

you have to make sure that the address(?) is spelled exactly the same as before(need to look in DB, which isn't ideal for everyone to have access to) to confirm they match

otherwise you have a separate restaurant entirely

going forward we should be able to assume that the person inputting the deals won't necessarily have access to the DB right

**Comment by brentonang** [comment]
What's the bug you are talking about?

**Comment by AdamDorwart** [comment]
This doesn't address the issue but I think only the restaurant name and first address line has to match to add to an existing restaurant.

**Comment by daleebz** [comment]
I know, still a tedious process. Just want to get more involved with the code/data management(I also have some experience). Also, want to get better with JS

**Comment by AdamDorwart** [comment]
This is in the wrong repo.
